services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:2424'
    volumes:
      - /var/local/gitlab/data:/var/opt/gitlab
      - /var/local/gitlab/logs:/var/log/gitlab
      - /var/local/gitlab/config:/etc/gitlab
    shm_size: '256m'
