---

- name: Copy sysctl.conf to the target
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  register: sysctl_conf

- name: Reload systctl.conf
  ansible.builtin.shell:
    cmd: sudo sysctl -p
  args:
    executable: /bin/bash
  when: sysctl_conf.changed

- name: Run systemctl restart docker
  ansible.builtin.shell:
    cmd: systemctl restart docker
  args:
    executable: /bin/bash
  when: sysctl_conf.changed

- name: Copy docker-compose.yml to the target
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /var/local/docker-compose-gitlab-sonarqube.yml
    owner: root
    group: root
    mode: '0644'

- name: Ensure gitlab config directory exists
  ansible.builtin.file:
    path: /var/local/gitlab/config
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Copy gitlab.rb to the target
  ansible.builtin.copy:
    src: gitlab.rb
    dest: /var/local/gitlab/config/gitlab.rb
    owner: root
    group: root
    mode: '0600'

- name: Ensure SSL directory exists for gitlab
  ansible.builtin.file:
    path: /var/local/gitlab/config/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate RSA private key for gitlab registry
  community.crypto.openssl_privatekey:
    path: /var/local/gitlab/config/ssl/gitlab.key
    size: 2048

- name: Create certificate signing request (CSR) for self-signed Gitlab certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: /var/local/gitlab/config/ssl/gitlab.key
    common_name: gitlab
    organization_name: JHU Devops, Inc.
    subject_alt_name:
      - "DNS:gitlab-registry"
  register: csr

- name: Generate self-signed certificate for gitlab registry
  community.crypto.x509_certificate:
    path: /var/local/gitlab/config/ssl/gitlab.crt
    privatekey_path: /var/local/gitlab/config/ssl/gitlab.key
    csr_content: "{{ csr.csr }}"
    provider: selfsigned

- name: Run docker-compose up
  ansible.builtin.shell:
    cmd: docker compose -f /var/local/docker-compose-gitlab-sonarqube.yml up -d
    chdir: /var/local/
  args:
    executable: /bin/bash
