---

- name: Copy sysctl.conf to the target
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  register: sysctl_conf

- name: Run sysctl -w vm.max_map_count=262144
  ansible.builtin.shell:
    cmd: sysctl -w vm.max_map_count=262144
  args:
    executable: /bin/bash

- name: Run systemctl restart docker
  ansible.builtin.shell:
    cmd: systemctl restart docker
  args:
    executable: /bin/bash
  when: sysctl_conf.changed

- name: Copy docker-compose.yml to the target
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /var/local/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

# - name: Init sonarqube docker volume
#   ansible.builtin.shell:
#     cmd: docker volume create local_sonarqube_extensions
#   args:
#     executable: /bin/bash

# - name: Download gitlab-sonarqube-plugin to extensions volume
#   ansible.builtin.shell:
#     cmd: docker run --rm -v local_sonarqube_extensions:/extensions busybox sh -c 'chmod 0770 /extensions && mkdir -p /extensions/plugins && chmod 0770 /extensions && wget https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/download/4.1.0-SNAPSHOT/sonar-gitlab-plugin-4.1.0-SNAPSHOT.jar -O /extensions/plugins/sonar-gitlab-plugin-4.1.0-SNAPSHOT.jar'
#   args:
#     executable: /bin/bash

- name: Run docker-compose up
  ansible.builtin.shell:
    cmd: docker compose -f /var/local/docker-compose.yml up -d
    chdir: /var/local/
  args:
    executable: /bin/bash
