services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  # ssh-agent:
  #   container_name: jenkins-ssh-agent
  #   image: jenkins/ssh-agent

volumes:
  jenkins_home:
