---
- name: Configure Hosts for DevOps Infra
  hosts: all
  become: yes
  roles:
    - host-confs

- name: Deploy GitLab and SonarQube
  hosts: all
  become: yes
  roles:
    - gitlab-sonarqube

- name: Deploy GitLab Runner
  hosts: all
  become: yes
  roles:
    - gitlab-runner
